#!/bin/bash
#
# Server Status MOTD Script
# Originally from: http://www.question-defense.com/2010/04/03/cent-os-how-to-make-a-custom-ssh-banner-with-current-system-statistics

# Get and define colors
ncolors=$(tput colors)
if [ $ncolors ] && [ $ncolors -ge 8 ]; then
  bold="$(tput bold)"
  underline="$(tput smul)"
  standout="$(tput smso)"
  normal="$(tput sgr0)"
  black="$(tput setaf 0)"
  red="$(tput setaf 1)"
  green="$(tput setaf 2)"
  yellow="$(tput setaf 3)"
  blue="$(tput setaf 4)"
  magenta="$(tput setaf 5)"
  cyan="$(tput setaf 6)"
  white="$(tput setaf 7)"

  dateStyle="$bold$magenta"
  propTitleStyle="$cyan"
  loginTitleStyle="$blue"
else
  normal=""
  dateStyle=""
  propTitleStyle=""
  loginTitleStyle=""
fi

 
CPUTIME=$(ps -eo pcpu | awk 'NR>1' | awk '{tot=tot+$1} END {print tot}')
CPUCORES=$(cat /proc/cpuinfo | grep -c processor)
UPTIME=$(echo `uptime` | awk '{ gsub(/,/, ""); print $3,$4 }')
LASTLOGINDATE=$(whoami | xargs last -aF | awk 'NR == 2 { print $3,$4,$5,$6,$7 }' | xargs -0 -I datestr date --date=datestr)
LASTLOGINHOST=$(whoami | xargs last -aF | awk 'NR == 2 { print $NF }')
LASTLOGINIP=$(whoami | xargs last -i | awk 'NR == 2 { print $3 }')
DISK_SPACE_USED=$(df --block-size="GB" / | sed s/GB//g | awk '{ size = $2 } { used = $3 } END { print used, "of", size }')
DISK_SPACE_PERCENT=$(df -h / | tail -n 1 | awk '{ print $5 }')
MEMORY_FREE_REAL=$(free -m | head -n 2 | tail -n 1 | awk {'print $4'})
MEMORY_FREE_CACHE=$(free -m | head -n 3 | tail -n 1 | awk {'print $4'})
MEMORY_TOTAL=$(free -m | head -n 2 | tail -n 1 | awk {'print $2'})
SWAP_USED=$(free -m | tail -n 1 | awk '{ size = $2 } { used = $3 } END { print used, "of", size }')

echo "
  System Status as of ${dateStyle}`date`${normal}
   
  ${propTitleStyle}Server Name:${normal}                `hostname`
  ${propTitleStyle}Host Name:${normal}                  `hostname -f`
  ${propTitleStyle}Public IP:${normal}                  `dig +short myip.opendns.com @resolver1.opendns.com`
  ${propTitleStyle}OS Version:${normal}                 `cat /etc/issue.net | head -1`
  ${propTitleStyle}System Uptime:${normal}              $UPTIME
  ${propTitleStyle}CPU Usage (average):${normal}        `echo $CPUTIME / $CPUCORES | bc`%
  ${propTitleStyle}Load Averages:${normal}              `cat /proc/loadavg`
  ${propTitleStyle}Memory free:${normal}                $MEMORY_FREE_REAL ($MEMORY_FREE_CACHE cached) of $MEMORY_TOTAL MB
  ${propTitleStyle}Swap in use:${normal}                $SWAP_USED MB
  ${propTitleStyle}Disk Space Used:${normal}            $DISK_SPACE_USED GB ($DISK_SPACE_PERCENT)
  
  ${loginTitleStyle}Last login Time:${normal}            $LASTLOGINDATE
  ${loginTitleStyle}Last login Host:${normal}            $LASTLOGINHOST
  ${loginTitleStyle}Last login IP:${normal}              $LASTLOGINIP
"
